In [13]:
import os as os
import pandas as pd
import xml.etree.ElementTree as ET
import numpy as np


abnormal_data=[]
normal_data=[]

# taking 10000 data sample for performance and testing

#read file loop and condition
# total file 111423
for i in range(111423) :
    if(i<10):
        file_name = "metabolites/hmdb_metabolites-{:02d}.xml".format(i)
    else:
        file_name = "metabolites/hmdb_metabolites-{}.xml".format(i)
    tree = ET.parse(file_name)
    root=tree.getroot()
    file=file_name[12:-4]
    
    value=0
    age="None"
    sex="Not Specified"
    info=""
    comment="None"

    #print("Abnormal Concentration\n ")
    for abnormal in root.findall('abnormal_concentrations'):

        for concentration in abnormal.findall('concentration'):
    #filter for blood specimen
            if(concentration.find('biospecimen').text=="Blood"):
                for attribute in concentration :
#                     print(attribute.tag,':',attribute.text)
                    if(attribute.tag=='concentration_value'):
                        value=attribute.text
                    if(attribute.tag=='patient_age'):
                        age=attribute.text
                    if(attribute.tag=='patient_sex'):
                        sex=attribute.text
                    if(attribute.tag=='patient_information'):
                        info=attribute.text
                    if(attribute.tag=='comment'):
                        comment=attribute.text
                        
    #append array for creating dataframe
                    toappend=[value,age,sex,info,comment,file]
                abnormal_data.append(toappend)



    #print reference(optional)                      
    #                     else : 
    #                         for reference in attribute.findall('reference'):
    #                             print(reference.tag," : ",reference.text)


    for normal in root.findall('normal_concentrations'):
        for concentration in normal.findall('concentration'):
            if(concentration.find('biospecimen').text=="Blood"):
                for attribute in concentration:
                        if(attribute.tag=='concentration_value'):
                            value=attribute.text
                        if(attribute.tag=='subject_age'):
                            age=attribute.text
                        if(attribute.tag=='subject_sex'):
                            sex=attribute.text
                        if(attribute.tag=='subject_condition'):
                            info=attribute.text
                        if(attribute.tag=='comment'):
                            comment=attribute.text
                        else:
                            comment="None"
                        toappend=[value,age,sex,info,comment,file]
                normal_data.append(toappend)

# create dataframe and write file in csv format   

# abnormal data
abndf = pd.DataFrame(abnormal_data,columns=['Value(uM)','Patient Age','Patient Sex','Patient Information','Comment','File'])                    
abndf.to_csv('Abnormal_Concentration.csv',header='False')
# abndf.head(20)
# normal data
ndf = pd.DataFrame(normal_data,columns=['Value(uM)','Subject Age','Subject Sex','Subject Information','Comment','File'])                    
ndf.to_csv('Normal_Concentration.csv',header='False')
# ndf.tail(50)

,Value(uM),Subject Age,Subject Sex,Subject Information,Comment,File
11938,None,Not Specified,Not Specified,N/A,None,hmdb_metabolites-41214
11939,20,Adult (>18 years old),Male,Normal,None,hmdb_metabolites-41478
11940,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-41531
11941,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-41531
11942,0.00000885 (0.00000678-0.0000115),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41545
11943,0.00000751 (0.0000058-0.00000971),Children (1-13 years old),Not Specified,Normal,None,hmdb_metabolites-41545
11944,0.00000357 (0.00000215-0.00000593),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41546
11945,0.000562 (0.000515-0.000611),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41551
11946,0.00338 (0.00295-0.00388),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41552
11947,0.00289 (0.00250-0.00334),Children (1-13 years old),Not Specified,Normal,None,hmdb_metabolites-41552
11948,0.000703 (0.000583-0.000845),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41553
11949,0.00108 (0.00101-0.00114),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41554
11950,0.000333 (0.000298-0.000350),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41555
11951,0.000323 (0.000284-0.000372),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41556
11952,0.0000710 (0.0000346-0.000146),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41559
11953,0.0000664 (0.0000319-0.000149),Children (1-13 years old),Not Specified,Normal,None,hmdb_metabolites-41559
11954,39.79 +/- 1.59,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-41560
11955,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-41641
11956,0.00043-0.00500,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-41696
11957,0.0000062 (0.0000042-0.0000091),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41718
11958,0.000600 +/- 0.000200,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-41720
11959,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41724
11960,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41724
11961,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41725
11962,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41725
11963,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41726
11964,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41726
11965,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41727
11966,None,Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-41727
11967,11.722 +/- 5.378,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-41957
11968,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-42043
11969,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-42117
11970,2010 +/- 530,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-42152
11971,2170 +/- 600,Adult (>18 years old),Male,Normal,None,hmdb_metabolites-42152
11972,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-42202
11973,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-42202
11974,<0.28,Adolescent (13-18 years old),Male,Normal,None,hmdb_metabolites-74096
11975,0.12 +/- 0.03,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-74096
11976,0.14(0.04),Adult (>18 years old),Both,Normal,None,hmdb_metabolites-74096
11977,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-74100
11978,None,Adult (>18 years old),Both,Normal,None,hmdb_metabolites-74100
11979,0.00402 (0.00362-0.00425),Adult (>18 years old),Not Specified,Normal,None,hmdb_metabolites-74104
11980,0.00507 (0.00442-0.00582),Children (1-13 years old),Not Specified,Normal,None,hmdb_metabolites-74104
11981,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91426
11982,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91427
11983,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91428
11984,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91429
11985,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91430
11986,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91431
11987,None,Adult (>18 years old),Female,Normal,None,hmdb_metabolites-91432